### ISSUE TITLE
Why did jampack convert some PNGs to JPGs?

### ISSUE THREAD

**Issue by inklesspen** [divriots/jampack#142]
I understand the logic in converting from jpg to webp, but I can't make sense of converting png to jpg. (The png in question is a screenshot of text; the png was 33k and the resulting jpg is 52k.)

[contents.png](https://github.com/divriots/jampack/assets/11397/7740d984-51b6-4b55-86ce-58bd3839c79f)
[contents.png.jpg](https://github.com/divriots/jampack/assets/11397/4225a60a-8dc7-4cc0-b14f-45287bc316d3)

**Comment by georges-gomes** [comment]
Hi!

I understand your questioning.
This can only happen when the image is "above-the-fold" so jampack favors Progressive JPEG. Because Progressive JPEG is better from a user experience as you get your content way earlier.
Jampack decided that a 52K Progressive JPEG is better than a 32K PNG when above-the-fold.
I'm not sure it's correct :) We would need to benchmark your result to be sure.

There is currently no option to change this behavior but I will probably to the following:
- Disabled Progressive JPEG if it's much bigger than the original PNG.
- Option is Enable/Disabled Progressive JPEG above-the-fold.

A lot of people are confused with the progressive JPEG above-the-fold so I should probably not have it by default and activate it via a configuration 👍
