### ISSUE TITLE
'Failed to create `_jampack` folder.' when running for the second time

### ISSUE THREAD

**Issue by apkostka** [divriots/jampack#150]
Hi, there: I've added jampack as a build step to my Jekyll site. Running it the first time works great, but the second time I get the error: 
`Failed to create `_jampack` folder.`
After debugging, it's because the `_jampack` folder within `_sites` already exists. It's not clear to me what that folder's purpose is, or whether it should persist between runs.

I can get it working by deleting the folder, but if it's necessary I'd rather avoid it. Looks like the issue is here: https://github.com/divriots/jampack/blob/e738a1ab7acdeac1295cb9b0da3c0162afde73b0/src/index.ts#L76

**Comment by georges-gomes** [comment]
This is "kind of" made on purpose because you don't want to run jampack twice on the same content (specially for images). If your build is incremental then it lead to terrible results.

2 options:
1) Fully delete your `_sites` folder before build, so it always start with a fresh website folder and not residual files as well.
2) Copy folder `_sites` to folder`_sites_jampack` (make sure to always delete `_site_jampack`) then run jampack on the new folder.

I think solution 1 is actually always required because you want a fresh build out before release and not being in a situation where old files are still living with new files.

My 2 cents

**Comment by apkostka** [comment]
Ah, ok, that actually makes a lot of sense. I had planned on running it in github actions so that wouldn't be an issue, this just came up while I was testing it. Thanks for the quick response @georges-gomes !

**Comment by reinthal** [comment]
Maybe provide a better user interface for this? 

`Failed to create _jampack folder`

sounds like something is broken. Been looking around for a while wondering what was wrong.

**Comment by georges-gomes** [comment]
@reinthal Yes, the new version already have that improved:
https://github.com/divriots/jampack/blob/main/src/index.ts#L79
