### ISSUE TITLE
Not generating multiple images

### ISSUE THREAD

**Issue by skhaz** [divriots/jampack#154]
I have the following code with only one image (already in AVIF)

```
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Ultratech Software">
    <title>Ultratech Software</title>
    <style>
      body {
        background-color: black;
        margin: 0;
      }
      .container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
      }
      img {
        width: 480px;
        height: 628px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <img src="macintosh.avif" alt="Ultratech Software">
    </div>
  </body>
</html>
```

When I check the output, there is no `srcset` on it. Why?

See the result: view-source:https://ultratech.software/

**Comment by georges-gomes** [comment]
Hi! Primarily because your original image is only 800px wide.

`jampack` makes images in steps of 300px.
A smaller image would be 500px wide.
Default configuration of `jampack` for `srcset` is minium 490x2.

`srcset_min_width` can be configured to get even smaller images.
https://jampack.divriots.com/configuration/

Enjoy

**Comment by skhaz** [comment]
Could you point out what is wrong? I did what the documentation mentions, except that I specify the width and height. Is that the problem?

<img width="842" alt="Screenshot 2024-04-15 at 10 05 43" src="https://github.com/divriots/jampack/assets/46259/d7ae0d3a-43b5-448e-8d77-fa1928e3ac66">

**Comment by georges-gomes** [comment]
Copy your HTML source here please

**Comment by georges-gomes** [comment]
I have never seen `jampack` transform `src="macintosh.avif"` 
into `src="[macintosh.avif](https://ultratech.software/macintosh.avif)"`
`Jampack` doesn't even know about `ultratech.software` so I think something else is processing the HTML after jampack

**Comment by skhaz** [comment]
It was GitHub... I will post again

```html
<!DOCTYPE html><html lang="en-US"><head><meta charset="UTF-8"><style>:where(img){height:auto}</style>
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="Ultratech Software">
<title>Ultratech Software</title>
<style>body{background-color:#000;margin:0}.container{justify-content:center;align-items:center;height:100vh;display:flex}.macintosh{width:480px;height:628px}.matrix{width:560px;height:560px}</style>
</head>
<body>
<div>
<div class="container">
<img class="macintosh" src="macintosh.avif" alt="Ultratech Software" fetchpriority="high" decoding="async" width="2560" height="3350">
</div>
<div class="container">
<img class="matrix" src="matrix.png.jpg" alt="Rodrigo Delduca" fetchpriority="high" decoding="async" width="560" height="560">
</div>
</div>
</body></html>
```

**Comment by georges-gomes** [comment]
I guess your `macintosh.avif` is still 800px wide - in the file.

My recommendation: Get a small PNG 1-to-1 pixel of your macintosh image and scale it pixelated with CSS.
https://css-tricks.com/almanac/properties/i/image-rendering/

You will get best quality possible in the smallest package.

**Comment by skhaz** [comment]
I dont think so, it is larger.

<img width="999" alt="Screenshot 2024-04-15 at 10 39 49" src="https://github.com/divriots/jampack/assets/46259/1e1ab818-07eb-41d4-b653-edcf6fd10fc6">

**Comment by georges-gomes** [comment]
Give a link with the 2 source files, maybe something if wrong with the avif processing.
Everything that I have been testing right now works.

**Comment by skhaz** [comment]
Source AVIF: https://raw.githubusercontent.com/ultratech/ultratech.software/master/macintosh.avif

Destination AVIF: https://ultratech.software/macintosh.avif

By the way, as you can see, lossy AVIF was used, and in some cases (from my experiments), besides degrading the image quality, the file size actually increases.

**Comment by georges-gomes** [comment]
I don't have the same result.

<img width="415" alt="image" src="https://github.com/divriots/jampack/assets/5250572/291aba90-9fc8-4217-b902-6c63bfd4d40a">

The reporting is 2 avif (but I only have 1) so it's doubling. So the 52K are for 2 images.

Your AVIF is untouched because `jampack` can't compress it better than it's already is so it keeps the original image.
The AVIF on disk is same size.

So that's why you don't have different files. jampack can't create smaller files so it doesn't replace the original file.

And this is probably due to the fact that your image is pixelated. When resized, antialiasing is created because the pixels don't divide perfectly so a lot of details are introduced that can't be compressed.

Again, for pixelated images, sizing a small image with CSS is much better than to push a very large image where all the pixels are multiplied.

**Comment by skhaz** [comment]
I understand. Very smart not to create larger images. Thank you very much for the help!
