### ISSUE TITLE
Warning for images being already lazy-loaded

### ISSUE THREAD

**Issue by tasiek** [divriots/jampack#46]
Jamstack processes images to be lazy-loaded (according to docs https://jampack.divriots.com/features/optimize-images/).
Although, for images having already lazy-loading applied (in our case, it comes from Gatsby, which has it enabled by default), it causes warnings.

`warn  Missing [src] on img - processing skipped.`

**Expected behaviour**
No warnings like above for images having `loading="lazy"` (even those not having `src` attribute).

**Comment by georges-gomes** [comment]
I'm not an expert in Gatsby but I think it does lazy load images using javascript.
It uses `data-src` and class `lazyimg` or something.
Could you send an HTML file example that I have a look?

3 options (not mutual exclusive):

1) We make `jampack` understand `data-src` when `src` is not here so a) doesn't warn b) doesn't try to add `loading="lazy"` c) `jampack` can optimize the image.

2) I would switch off lazy loading from Gatsby because it's done with Javascript instead of using native browser lazy loading that `jampack` uses. You can do that https://github.com/gatsbyjs/gatsby/pull/7083 but maybe there is a way to do it globally. I think lazy loading in Javascript is a bit obsolete. The Javascript for lazy loading is impacting performance unnecessarily.

**Comment by georges-gomes** [comment]
Done, no warning for images without `src` but with `data-src`

https://github.com/divriots/jampack/commit/f0c9a355fa47d8a0648dc8c4422a95b8eac3ee4f

Maybe later it would be nice to try to optimize these images... Most of the time, it's already done so we just back off from processing.

**Comment by tasiek** [comment]
@georges-gomes Oh great! Just disabling the warning is quite sufficient in this case. 

If we speak of Gatsby, those images are optimized anyways - it comes from StaticImage Gatsby's component. Unless `jampack` could optimize them even more, but I guess it doesn't matter that much.
